:verbose: false
:concurrency:  1
:queues:
  - [rollbacks, 2]
  - [sync, 2]
  - [default, 5]
:schedule:
  UpdatesSynchronizerWorker:
    cron: "0 0-9,18-23 * * *"
    description: "UpdatesSynchronizerWorker will run at every 0th minute past the 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 18, 19, 20, 21, 22 and 23rd hour."
